// Mocks generated by Mockito 5.4.6 from annotations
// in docker_controller/test/mocks.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;
import 'dart:ui' as _i8;

import 'package:dio/dio.dart' as _i2;
import 'package:docker_controller/models/connection_config.dart' as _i7;
import 'package:docker_controller/models/docker_container.dart' as _i5;
import 'package:docker_controller/models/docker_image.dart' as _i15;
import 'package:docker_controller/providers/auth_provider.dart' as _i6;
import 'package:docker_controller/services/auth_service.dart' as _i10;
import 'package:docker_controller/services/container_service.dart' as _i3;
import 'package:docker_controller/services/dio_client.dart' as _i12;
import 'package:docker_controller/services/image_service.dart' as _i14;
import 'package:docker_controller/services/notification_service.dart' as _i13;
import 'package:docker_controller/services/system_service.dart' as _i11;
import 'package:mockito/mockito.dart' as _i1;
import 'package:shared_preferences/shared_preferences.dart' as _i9;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeDio_0 extends _i1.SmartFake implements _i2.Dio {
  _FakeDio_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [ContainerService].
///
/// See the documentation for Mockito's code generation for more information.
class MockContainerService extends _i1.Mock implements _i3.ContainerService {
  MockContainerService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<List<_i5.DockerContainer>> getContainers() =>
      (super.noSuchMethod(
            Invocation.method(#getContainers, []),
            returnValue: _i4.Future<List<_i5.DockerContainer>>.value(
              <_i5.DockerContainer>[],
            ),
          )
          as _i4.Future<List<_i5.DockerContainer>>);

  @override
  _i4.Future<_i5.DockerContainer?> getContainerInfo(String? containerId) =>
      (super.noSuchMethod(
            Invocation.method(#getContainerInfo, [containerId]),
            returnValue: _i4.Future<_i5.DockerContainer?>.value(),
          )
          as _i4.Future<_i5.DockerContainer?>);

  @override
  _i4.Future<Map<String, dynamic>?> getContainerStats(String? containerId) =>
      (super.noSuchMethod(
            Invocation.method(#getContainerStats, [containerId]),
            returnValue: _i4.Future<Map<String, dynamic>?>.value(),
          )
          as _i4.Future<Map<String, dynamic>?>);

  @override
  _i4.Future<String?> getContainerLogs(
    String? containerId, {
    int? tail = 200,
    String? since,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #getContainerLogs,
              [containerId],
              {#tail: tail, #since: since},
            ),
            returnValue: _i4.Future<String?>.value(),
          )
          as _i4.Future<String?>);

  @override
  _i4.Future<bool> startContainer(String? containerId) =>
      (super.noSuchMethod(
            Invocation.method(#startContainer, [containerId]),
            returnValue: _i4.Future<bool>.value(false),
          )
          as _i4.Future<bool>);

  @override
  _i4.Future<bool> stopContainer(String? containerId) =>
      (super.noSuchMethod(
            Invocation.method(#stopContainer, [containerId]),
            returnValue: _i4.Future<bool>.value(false),
          )
          as _i4.Future<bool>);

  @override
  _i4.Future<bool> pauseContainer(String? containerId) =>
      (super.noSuchMethod(
            Invocation.method(#pauseContainer, [containerId]),
            returnValue: _i4.Future<bool>.value(false),
          )
          as _i4.Future<bool>);

  @override
  _i4.Future<bool> resumeContainer(String? containerId) =>
      (super.noSuchMethod(
            Invocation.method(#resumeContainer, [containerId]),
            returnValue: _i4.Future<bool>.value(false),
          )
          as _i4.Future<bool>);

  @override
  _i4.Future<bool> restartContainer(String? containerId) =>
      (super.noSuchMethod(
            Invocation.method(#restartContainer, [containerId]),
            returnValue: _i4.Future<bool>.value(false),
          )
          as _i4.Future<bool>);

  @override
  _i4.Future<bool> killContainer(String? containerId) =>
      (super.noSuchMethod(
            Invocation.method(#killContainer, [containerId]),
            returnValue: _i4.Future<bool>.value(false),
          )
          as _i4.Future<bool>);

  @override
  _i4.Future<bool> removeContainer(String? containerId) =>
      (super.noSuchMethod(
            Invocation.method(#removeContainer, [containerId]),
            returnValue: _i4.Future<bool>.value(false),
          )
          as _i4.Future<bool>);

  @override
  _i4.Future<bool> renameContainer(String? containerId, String? newName) =>
      (super.noSuchMethod(
            Invocation.method(#renameContainer, [containerId, newName]),
            returnValue: _i4.Future<bool>.value(false),
          )
          as _i4.Future<bool>);

  @override
  _i4.Future<String?> createContainer(Map<String, dynamic>? containerConfig) =>
      (super.noSuchMethod(
            Invocation.method(#createContainer, [containerConfig]),
            returnValue: _i4.Future<String?>.value(),
          )
          as _i4.Future<String?>);

  @override
  _i4.Future<String?> createAndStartContainer(
    Map<String, dynamic>? containerConfig,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#createAndStartContainer, [containerConfig]),
            returnValue: _i4.Future<String?>.value(),
          )
          as _i4.Future<String?>);
}

/// A class which mocks [AuthProvider].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthProvider extends _i1.Mock implements _i6.AuthProvider {
  MockAuthProvider() {
    _i1.throwOnMissingStub(this);
  }

  @override
  bool get isConnected =>
      (super.noSuchMethod(Invocation.getter(#isConnected), returnValue: false)
          as bool);

  @override
  bool get isConnecting =>
      (super.noSuchMethod(Invocation.getter(#isConnecting), returnValue: false)
          as bool);

  @override
  List<String> get connectionHistory =>
      (super.noSuchMethod(
            Invocation.getter(#connectionHistory),
            returnValue: <String>[],
          )
          as List<String>);

  @override
  bool get hasListeners =>
      (super.noSuchMethod(Invocation.getter(#hasListeners), returnValue: false)
          as bool);

  @override
  _i4.Future<void> connect(
    _i7.ConnectionConfig? config, {
    String? username,
    String? password,
    bool? persist = false,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #connect,
              [config],
              {#username: username, #password: password, #persist: persist},
            ),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> logout() =>
      (super.noSuchMethod(
            Invocation.method(#logout, []),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  void clearError() => super.noSuchMethod(
    Invocation.method(#clearError, []),
    returnValueForMissingStub: null,
  );

  @override
  void addListener(_i8.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#addListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void removeListener(_i8.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#removeListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );

  @override
  void notifyListeners() => super.noSuchMethod(
    Invocation.method(#notifyListeners, []),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [SharedPreferences].
///
/// See the documentation for Mockito's code generation for more information.
class MockSharedPreferences extends _i1.Mock implements _i9.SharedPreferences {
  MockSharedPreferences() {
    _i1.throwOnMissingStub(this);
  }

  @override
  Set<String> getKeys() =>
      (super.noSuchMethod(
            Invocation.method(#getKeys, []),
            returnValue: <String>{},
          )
          as Set<String>);

  @override
  Object? get(String? key) =>
      (super.noSuchMethod(Invocation.method(#get, [key])) as Object?);

  @override
  bool? getBool(String? key) =>
      (super.noSuchMethod(Invocation.method(#getBool, [key])) as bool?);

  @override
  int? getInt(String? key) =>
      (super.noSuchMethod(Invocation.method(#getInt, [key])) as int?);

  @override
  double? getDouble(String? key) =>
      (super.noSuchMethod(Invocation.method(#getDouble, [key])) as double?);

  @override
  String? getString(String? key) =>
      (super.noSuchMethod(Invocation.method(#getString, [key])) as String?);

  @override
  bool containsKey(String? key) =>
      (super.noSuchMethod(
            Invocation.method(#containsKey, [key]),
            returnValue: false,
          )
          as bool);

  @override
  List<String>? getStringList(String? key) =>
      (super.noSuchMethod(Invocation.method(#getStringList, [key]))
          as List<String>?);

  @override
  _i4.Future<bool> setBool(String? key, bool? value) =>
      (super.noSuchMethod(
            Invocation.method(#setBool, [key, value]),
            returnValue: _i4.Future<bool>.value(false),
          )
          as _i4.Future<bool>);

  @override
  _i4.Future<bool> setInt(String? key, int? value) =>
      (super.noSuchMethod(
            Invocation.method(#setInt, [key, value]),
            returnValue: _i4.Future<bool>.value(false),
          )
          as _i4.Future<bool>);

  @override
  _i4.Future<bool> setDouble(String? key, double? value) =>
      (super.noSuchMethod(
            Invocation.method(#setDouble, [key, value]),
            returnValue: _i4.Future<bool>.value(false),
          )
          as _i4.Future<bool>);

  @override
  _i4.Future<bool> setString(String? key, String? value) =>
      (super.noSuchMethod(
            Invocation.method(#setString, [key, value]),
            returnValue: _i4.Future<bool>.value(false),
          )
          as _i4.Future<bool>);

  @override
  _i4.Future<bool> setStringList(String? key, List<String>? value) =>
      (super.noSuchMethod(
            Invocation.method(#setStringList, [key, value]),
            returnValue: _i4.Future<bool>.value(false),
          )
          as _i4.Future<bool>);

  @override
  _i4.Future<bool> remove(String? key) =>
      (super.noSuchMethod(
            Invocation.method(#remove, [key]),
            returnValue: _i4.Future<bool>.value(false),
          )
          as _i4.Future<bool>);

  @override
  _i4.Future<bool> commit() =>
      (super.noSuchMethod(
            Invocation.method(#commit, []),
            returnValue: _i4.Future<bool>.value(false),
          )
          as _i4.Future<bool>);

  @override
  _i4.Future<bool> clear() =>
      (super.noSuchMethod(
            Invocation.method(#clear, []),
            returnValue: _i4.Future<bool>.value(false),
          )
          as _i4.Future<bool>);

  @override
  _i4.Future<void> reload() =>
      (super.noSuchMethod(
            Invocation.method(#reload, []),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);
}

/// A class which mocks [AuthService].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthService extends _i1.Mock implements _i10.AuthService {
  MockAuthService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<String?> login(String? username, String? password) =>
      (super.noSuchMethod(
            Invocation.method(#login, [username, password]),
            returnValue: _i4.Future<String?>.value(),
          )
          as _i4.Future<String?>);
}

/// A class which mocks [SystemService].
///
/// See the documentation for Mockito's code generation for more information.
class MockSystemService extends _i1.Mock implements _i11.SystemService {
  MockSystemService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<Map<String, dynamic>?> getSystemInfo() =>
      (super.noSuchMethod(
            Invocation.method(#getSystemInfo, []),
            returnValue: _i4.Future<Map<String, dynamic>?>.value(),
          )
          as _i4.Future<Map<String, dynamic>?>);

  @override
  _i4.Future<bool> testConnection() =>
      (super.noSuchMethod(
            Invocation.method(#testConnection, []),
            returnValue: _i4.Future<bool>.value(false),
          )
          as _i4.Future<bool>);

  @override
  _i4.Future<Map<String, dynamic>?> getFirebaseConfig() =>
      (super.noSuchMethod(
            Invocation.method(#getFirebaseConfig, []),
            returnValue: _i4.Future<Map<String, dynamic>?>.value(),
          )
          as _i4.Future<Map<String, dynamic>?>);

  @override
  _i4.Future<Map<String, dynamic>> getSystemMetrics([String? window = '30m']) =>
      (super.noSuchMethod(
            Invocation.method(#getSystemMetrics, [window]),
            returnValue: _i4.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i4.Future<Map<String, dynamic>>);
}

/// A class which mocks [DioClient].
///
/// See the documentation for Mockito's code generation for more information.
class MockDioClient extends _i1.Mock implements _i12.DioClient {
  MockDioClient() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.Dio get dio =>
      (super.noSuchMethod(
            Invocation.getter(#dio),
            returnValue: _FakeDio_0(this, Invocation.getter(#dio)),
          )
          as _i2.Dio);

  @override
  void updateConfig(_i7.ConnectionConfig? config) => super.noSuchMethod(
    Invocation.method(#updateConfig, [config]),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [NotificationService].
///
/// See the documentation for Mockito's code generation for more information.
class MockNotificationService extends _i1.Mock
    implements _i13.NotificationService {
  MockNotificationService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Stream<Map<String, dynamic>> get onNotificationReceived =>
      (super.noSuchMethod(
            Invocation.getter(#onNotificationReceived),
            returnValue: _i4.Stream<Map<String, dynamic>>.empty(),
          )
          as _i4.Stream<Map<String, dynamic>>);

  @override
  bool get isInitialized =>
      (super.noSuchMethod(Invocation.getter(#isInitialized), returnValue: false)
          as bool);

  @override
  bool get dockerMonitoringEnabled =>
      (super.noSuchMethod(
            Invocation.getter(#dockerMonitoringEnabled),
            returnValue: false,
          )
          as bool);

  @override
  bool get resourceMonitoringEnabled =>
      (super.noSuchMethod(
            Invocation.getter(#resourceMonitoringEnabled),
            returnValue: false,
          )
          as bool);

  @override
  Map<String, double> get thresholds =>
      (super.noSuchMethod(
            Invocation.getter(#thresholds),
            returnValue: <String, double>{},
          )
          as Map<String, double>);

  @override
  _i4.Future<void> initialize() =>
      (super.noSuchMethod(
            Invocation.method(#initialize, []),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> registerForNotifications() =>
      (super.noSuchMethod(
            Invocation.method(#registerForNotifications, []),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> unregisterFromNotifications({String? baseUrl}) =>
      (super.noSuchMethod(
            Invocation.method(#unregisterFromNotifications, [], {
              #baseUrl: baseUrl,
            }),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> updateThresholds({
    double? cpuThreshold,
    double? memoryThreshold,
    double? gpuLoadThreshold,
    double? gpuMemoryThreshold,
    String? baseUrl,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#updateThresholds, [], {
              #cpuThreshold: cpuThreshold,
              #memoryThreshold: memoryThreshold,
              #gpuLoadThreshold: gpuLoadThreshold,
              #gpuMemoryThreshold: gpuMemoryThreshold,
              #baseUrl: baseUrl,
            }),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<Map<String, dynamic>> getMonitoringStatus() =>
      (super.noSuchMethod(
            Invocation.method(#getMonitoringStatus, []),
            returnValue: _i4.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i4.Future<Map<String, dynamic>>);

  @override
  _i4.Future<void> sendTestNotification(String? notificationType) =>
      (super.noSuchMethod(
            Invocation.method(#sendTestNotification, [notificationType]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> setNotificationPreferences({
    bool? dockerMonitoring,
    bool? resourceMonitoring,
    String? url,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#setNotificationPreferences, [], {
              #dockerMonitoring: dockerMonitoring,
              #resourceMonitoring: resourceMonitoring,
              #url: url,
            }),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> loadPreferences(String? url) =>
      (super.noSuchMethod(
            Invocation.method(#loadPreferences, [url]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> savePreferences(String? url) =>
      (super.noSuchMethod(
            Invocation.method(#savePreferences, [url]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> dispose() =>
      (super.noSuchMethod(
            Invocation.method(#dispose, []),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);
}

/// A class which mocks [ImageService].
///
/// See the documentation for Mockito's code generation for more information.
class MockImageService extends _i1.Mock implements _i14.ImageService {
  MockImageService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<List<_i15.DockerImage>> getImages() =>
      (super.noSuchMethod(
            Invocation.method(#getImages, []),
            returnValue: _i4.Future<List<_i15.DockerImage>>.value(
              <_i15.DockerImage>[],
            ),
          )
          as _i4.Future<List<_i15.DockerImage>>);

  @override
  _i4.Future<bool> pullImage(String? imageName, String? tag) =>
      (super.noSuchMethod(
            Invocation.method(#pullImage, [imageName, tag]),
            returnValue: _i4.Future<bool>.value(false),
          )
          as _i4.Future<bool>);

  @override
  _i4.Future<bool> imageExists(String? imageName, String? tag) =>
      (super.noSuchMethod(
            Invocation.method(#imageExists, [imageName, tag]),
            returnValue: _i4.Future<bool>.value(false),
          )
          as _i4.Future<bool>);

  @override
  _i4.Future<bool> ensureImageExists(String? imageName, String? tag) =>
      (super.noSuchMethod(
            Invocation.method(#ensureImageExists, [imageName, tag]),
            returnValue: _i4.Future<bool>.value(false),
          )
          as _i4.Future<bool>);

  @override
  _i4.Future<bool> removeImage(String? imageId) =>
      (super.noSuchMethod(
            Invocation.method(#removeImage, [imageId]),
            returnValue: _i4.Future<bool>.value(false),
          )
          as _i4.Future<bool>);
}
