// Mocks generated by Mockito 5.4.6 from annotations
// in docker_controller/test/mocks.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;
import 'dart:ui' as _i11;

import 'package:dio/dio.dart' as _i2;
import 'package:docker_controller/core/utils/result.dart' as _i5;
import 'package:docker_controller/models/app_error.dart' as _i7;
import 'package:docker_controller/models/connection_config.dart' as _i10;
import 'package:docker_controller/models/docker_container.dart' as _i6;
import 'package:docker_controller/models/docker_image.dart' as _i18;
import 'package:docker_controller/models/docker_network.dart' as _i23;
import 'package:docker_controller/models/docker_volume.dart' as _i21;
import 'package:docker_controller/providers/auth_provider.dart' as _i9;
import 'package:docker_controller/services/auth_service.dart' as _i13;
import 'package:docker_controller/services/connection_storage_service.dart'
    as _i24;
import 'package:docker_controller/services/container_service.dart' as _i3;
import 'package:docker_controller/services/dio_client.dart' as _i15;
import 'package:docker_controller/services/docker_service.dart' as _i19;
import 'package:docker_controller/services/firebase_service.dart' as _i26;
import 'package:docker_controller/services/image_service.dart' as _i17;
import 'package:docker_controller/services/network_service.dart' as _i22;
import 'package:docker_controller/services/notification_service.dart' as _i16;
import 'package:docker_controller/services/preferences_service.dart' as _i25;
import 'package:docker_controller/services/system_service.dart' as _i14;
import 'package:docker_controller/services/volume_service.dart' as _i20;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i8;
import 'package:shared_preferences/shared_preferences.dart' as _i12;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeDio_0 extends _i1.SmartFake implements _i2.Dio {
  _FakeDio_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeBaseOptions_1 extends _i1.SmartFake implements _i2.BaseOptions {
  _FakeBaseOptions_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeHttpClientAdapter_2 extends _i1.SmartFake
    implements _i2.HttpClientAdapter {
  _FakeHttpClientAdapter_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeTransformer_3 extends _i1.SmartFake implements _i2.Transformer {
  _FakeTransformer_3(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeInterceptors_4 extends _i1.SmartFake implements _i2.Interceptors {
  _FakeInterceptors_4(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeResponse_5<T1> extends _i1.SmartFake implements _i2.Response<T1> {
  _FakeResponse_5(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [ContainerService].
///
/// See the documentation for Mockito's code generation for more information.
class MockContainerService extends _i1.Mock implements _i3.ContainerService {
  MockContainerService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i5.Result<List<_i6.DockerContainer>, _i7.AppError>>
  getContainers() =>
      (super.noSuchMethod(
            Invocation.method(#getContainers, []),
            returnValue:
                _i4.Future<
                  _i5.Result<List<_i6.DockerContainer>, _i7.AppError>
                >.value(
                  _i8.dummyValue<
                    _i5.Result<List<_i6.DockerContainer>, _i7.AppError>
                  >(this, Invocation.method(#getContainers, [])),
                ),
          )
          as _i4.Future<_i5.Result<List<_i6.DockerContainer>, _i7.AppError>>);

  @override
  _i4.Future<_i5.Result<_i6.DockerContainer, _i7.AppError>> getContainerInfo(
    String? containerId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getContainerInfo, [containerId]),
            returnValue:
                _i4.Future<_i5.Result<_i6.DockerContainer, _i7.AppError>>.value(
                  _i8.dummyValue<_i5.Result<_i6.DockerContainer, _i7.AppError>>(
                    this,
                    Invocation.method(#getContainerInfo, [containerId]),
                  ),
                ),
          )
          as _i4.Future<_i5.Result<_i6.DockerContainer, _i7.AppError>>);

  @override
  _i4.Future<_i5.Result<Map<String, dynamic>, _i7.AppError>> getContainerStats(
    String? containerId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getContainerStats, [containerId]),
            returnValue:
                _i4.Future<
                  _i5.Result<Map<String, dynamic>, _i7.AppError>
                >.value(
                  _i8.dummyValue<
                    _i5.Result<Map<String, dynamic>, _i7.AppError>
                  >(this, Invocation.method(#getContainerStats, [containerId])),
                ),
          )
          as _i4.Future<_i5.Result<Map<String, dynamic>, _i7.AppError>>);

  @override
  _i4.Future<_i5.Result<String, _i7.AppError>> getContainerLogs(
    String? containerId, {
    int? tail = 200,
    String? since,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #getContainerLogs,
              [containerId],
              {#tail: tail, #since: since},
            ),
            returnValue: _i4.Future<_i5.Result<String, _i7.AppError>>.value(
              _i8.dummyValue<_i5.Result<String, _i7.AppError>>(
                this,
                Invocation.method(
                  #getContainerLogs,
                  [containerId],
                  {#tail: tail, #since: since},
                ),
              ),
            ),
          )
          as _i4.Future<_i5.Result<String, _i7.AppError>>);

  @override
  _i4.Future<_i5.Result<bool, _i7.AppError>> startContainer(
    String? containerId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#startContainer, [containerId]),
            returnValue: _i4.Future<_i5.Result<bool, _i7.AppError>>.value(
              _i8.dummyValue<_i5.Result<bool, _i7.AppError>>(
                this,
                Invocation.method(#startContainer, [containerId]),
              ),
            ),
          )
          as _i4.Future<_i5.Result<bool, _i7.AppError>>);

  @override
  _i4.Future<_i5.Result<bool, _i7.AppError>> stopContainer(
    String? containerId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#stopContainer, [containerId]),
            returnValue: _i4.Future<_i5.Result<bool, _i7.AppError>>.value(
              _i8.dummyValue<_i5.Result<bool, _i7.AppError>>(
                this,
                Invocation.method(#stopContainer, [containerId]),
              ),
            ),
          )
          as _i4.Future<_i5.Result<bool, _i7.AppError>>);

  @override
  _i4.Future<_i5.Result<bool, _i7.AppError>> pauseContainer(
    String? containerId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#pauseContainer, [containerId]),
            returnValue: _i4.Future<_i5.Result<bool, _i7.AppError>>.value(
              _i8.dummyValue<_i5.Result<bool, _i7.AppError>>(
                this,
                Invocation.method(#pauseContainer, [containerId]),
              ),
            ),
          )
          as _i4.Future<_i5.Result<bool, _i7.AppError>>);

  @override
  _i4.Future<_i5.Result<bool, _i7.AppError>> resumeContainer(
    String? containerId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#resumeContainer, [containerId]),
            returnValue: _i4.Future<_i5.Result<bool, _i7.AppError>>.value(
              _i8.dummyValue<_i5.Result<bool, _i7.AppError>>(
                this,
                Invocation.method(#resumeContainer, [containerId]),
              ),
            ),
          )
          as _i4.Future<_i5.Result<bool, _i7.AppError>>);

  @override
  _i4.Future<_i5.Result<bool, _i7.AppError>> restartContainer(
    String? containerId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#restartContainer, [containerId]),
            returnValue: _i4.Future<_i5.Result<bool, _i7.AppError>>.value(
              _i8.dummyValue<_i5.Result<bool, _i7.AppError>>(
                this,
                Invocation.method(#restartContainer, [containerId]),
              ),
            ),
          )
          as _i4.Future<_i5.Result<bool, _i7.AppError>>);

  @override
  _i4.Future<_i5.Result<bool, _i7.AppError>> killContainer(
    String? containerId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#killContainer, [containerId]),
            returnValue: _i4.Future<_i5.Result<bool, _i7.AppError>>.value(
              _i8.dummyValue<_i5.Result<bool, _i7.AppError>>(
                this,
                Invocation.method(#killContainer, [containerId]),
              ),
            ),
          )
          as _i4.Future<_i5.Result<bool, _i7.AppError>>);

  @override
  _i4.Future<_i5.Result<bool, _i7.AppError>> removeContainer(
    String? containerId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#removeContainer, [containerId]),
            returnValue: _i4.Future<_i5.Result<bool, _i7.AppError>>.value(
              _i8.dummyValue<_i5.Result<bool, _i7.AppError>>(
                this,
                Invocation.method(#removeContainer, [containerId]),
              ),
            ),
          )
          as _i4.Future<_i5.Result<bool, _i7.AppError>>);

  @override
  _i4.Future<_i5.Result<bool, _i7.AppError>> renameContainer(
    String? containerId,
    String? newName,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#renameContainer, [containerId, newName]),
            returnValue: _i4.Future<_i5.Result<bool, _i7.AppError>>.value(
              _i8.dummyValue<_i5.Result<bool, _i7.AppError>>(
                this,
                Invocation.method(#renameContainer, [containerId, newName]),
              ),
            ),
          )
          as _i4.Future<_i5.Result<bool, _i7.AppError>>);

  @override
  _i4.Future<_i5.Result<String, _i7.AppError>> createContainer(
    Map<String, dynamic>? containerConfig,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#createContainer, [containerConfig]),
            returnValue: _i4.Future<_i5.Result<String, _i7.AppError>>.value(
              _i8.dummyValue<_i5.Result<String, _i7.AppError>>(
                this,
                Invocation.method(#createContainer, [containerConfig]),
              ),
            ),
          )
          as _i4.Future<_i5.Result<String, _i7.AppError>>);

  @override
  _i4.Future<_i5.Result<String, _i7.AppError>> createAndStartContainer(
    Map<String, dynamic>? containerConfig,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#createAndStartContainer, [containerConfig]),
            returnValue: _i4.Future<_i5.Result<String, _i7.AppError>>.value(
              _i8.dummyValue<_i5.Result<String, _i7.AppError>>(
                this,
                Invocation.method(#createAndStartContainer, [containerConfig]),
              ),
            ),
          )
          as _i4.Future<_i5.Result<String, _i7.AppError>>);
}

/// A class which mocks [AuthProvider].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthProvider extends _i1.Mock implements _i9.AuthProvider {
  MockAuthProvider() {
    _i1.throwOnMissingStub(this);
  }

  @override
  bool get isConnected =>
      (super.noSuchMethod(Invocation.getter(#isConnected), returnValue: false)
          as bool);

  @override
  bool get isConnecting =>
      (super.noSuchMethod(Invocation.getter(#isConnecting), returnValue: false)
          as bool);

  @override
  List<String> get connectionHistory =>
      (super.noSuchMethod(
            Invocation.getter(#connectionHistory),
            returnValue: <String>[],
          )
          as List<String>);

  @override
  bool get hasListeners =>
      (super.noSuchMethod(Invocation.getter(#hasListeners), returnValue: false)
          as bool);

  @override
  _i4.Future<void> init() =>
      (super.noSuchMethod(
            Invocation.method(#init, []),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> connect(
    _i10.ConnectionConfig? config, {
    String? username,
    String? password,
    bool? persist = false,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #connect,
              [config],
              {#username: username, #password: password, #persist: persist},
            ),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> logout() =>
      (super.noSuchMethod(
            Invocation.method(#logout, []),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  void clearError() => super.noSuchMethod(
    Invocation.method(#clearError, []),
    returnValueForMissingStub: null,
  );

  @override
  void addListener(_i11.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#addListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void removeListener(_i11.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#removeListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );

  @override
  void notifyListeners() => super.noSuchMethod(
    Invocation.method(#notifyListeners, []),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [SharedPreferences].
///
/// See the documentation for Mockito's code generation for more information.
class MockSharedPreferences extends _i1.Mock implements _i12.SharedPreferences {
  MockSharedPreferences() {
    _i1.throwOnMissingStub(this);
  }

  @override
  Set<String> getKeys() =>
      (super.noSuchMethod(
            Invocation.method(#getKeys, []),
            returnValue: <String>{},
          )
          as Set<String>);

  @override
  Object? get(String? key) =>
      (super.noSuchMethod(Invocation.method(#get, [key])) as Object?);

  @override
  bool? getBool(String? key) =>
      (super.noSuchMethod(Invocation.method(#getBool, [key])) as bool?);

  @override
  int? getInt(String? key) =>
      (super.noSuchMethod(Invocation.method(#getInt, [key])) as int?);

  @override
  double? getDouble(String? key) =>
      (super.noSuchMethod(Invocation.method(#getDouble, [key])) as double?);

  @override
  String? getString(String? key) =>
      (super.noSuchMethod(Invocation.method(#getString, [key])) as String?);

  @override
  bool containsKey(String? key) =>
      (super.noSuchMethod(
            Invocation.method(#containsKey, [key]),
            returnValue: false,
          )
          as bool);

  @override
  List<String>? getStringList(String? key) =>
      (super.noSuchMethod(Invocation.method(#getStringList, [key]))
          as List<String>?);

  @override
  _i4.Future<bool> setBool(String? key, bool? value) =>
      (super.noSuchMethod(
            Invocation.method(#setBool, [key, value]),
            returnValue: _i4.Future<bool>.value(false),
          )
          as _i4.Future<bool>);

  @override
  _i4.Future<bool> setInt(String? key, int? value) =>
      (super.noSuchMethod(
            Invocation.method(#setInt, [key, value]),
            returnValue: _i4.Future<bool>.value(false),
          )
          as _i4.Future<bool>);

  @override
  _i4.Future<bool> setDouble(String? key, double? value) =>
      (super.noSuchMethod(
            Invocation.method(#setDouble, [key, value]),
            returnValue: _i4.Future<bool>.value(false),
          )
          as _i4.Future<bool>);

  @override
  _i4.Future<bool> setString(String? key, String? value) =>
      (super.noSuchMethod(
            Invocation.method(#setString, [key, value]),
            returnValue: _i4.Future<bool>.value(false),
          )
          as _i4.Future<bool>);

  @override
  _i4.Future<bool> setStringList(String? key, List<String>? value) =>
      (super.noSuchMethod(
            Invocation.method(#setStringList, [key, value]),
            returnValue: _i4.Future<bool>.value(false),
          )
          as _i4.Future<bool>);

  @override
  _i4.Future<bool> remove(String? key) =>
      (super.noSuchMethod(
            Invocation.method(#remove, [key]),
            returnValue: _i4.Future<bool>.value(false),
          )
          as _i4.Future<bool>);

  @override
  _i4.Future<bool> commit() =>
      (super.noSuchMethod(
            Invocation.method(#commit, []),
            returnValue: _i4.Future<bool>.value(false),
          )
          as _i4.Future<bool>);

  @override
  _i4.Future<bool> clear() =>
      (super.noSuchMethod(
            Invocation.method(#clear, []),
            returnValue: _i4.Future<bool>.value(false),
          )
          as _i4.Future<bool>);

  @override
  _i4.Future<void> reload() =>
      (super.noSuchMethod(
            Invocation.method(#reload, []),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);
}

/// A class which mocks [AuthService].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthService extends _i1.Mock implements _i13.AuthService {
  MockAuthService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i5.Result<String, _i7.AppError>> login(
    String? username,
    String? password,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#login, [username, password]),
            returnValue: _i4.Future<_i5.Result<String, _i7.AppError>>.value(
              _i8.dummyValue<_i5.Result<String, _i7.AppError>>(
                this,
                Invocation.method(#login, [username, password]),
              ),
            ),
          )
          as _i4.Future<_i5.Result<String, _i7.AppError>>);
}

/// A class which mocks [SystemService].
///
/// See the documentation for Mockito's code generation for more information.
class MockSystemService extends _i1.Mock implements _i14.SystemService {
  MockSystemService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i5.Result<Map<String, dynamic>, _i7.AppError>> getSystemInfo() =>
      (super.noSuchMethod(
            Invocation.method(#getSystemInfo, []),
            returnValue:
                _i4.Future<
                  _i5.Result<Map<String, dynamic>, _i7.AppError>
                >.value(
                  _i8.dummyValue<
                    _i5.Result<Map<String, dynamic>, _i7.AppError>
                  >(this, Invocation.method(#getSystemInfo, [])),
                ),
          )
          as _i4.Future<_i5.Result<Map<String, dynamic>, _i7.AppError>>);

  @override
  _i4.Future<_i5.Result<bool, _i7.AppError>> testConnection() =>
      (super.noSuchMethod(
            Invocation.method(#testConnection, []),
            returnValue: _i4.Future<_i5.Result<bool, _i7.AppError>>.value(
              _i8.dummyValue<_i5.Result<bool, _i7.AppError>>(
                this,
                Invocation.method(#testConnection, []),
              ),
            ),
          )
          as _i4.Future<_i5.Result<bool, _i7.AppError>>);

  @override
  _i4.Future<_i5.Result<Map<String, dynamic>, _i7.AppError>>
  getFirebaseConfig() =>
      (super.noSuchMethod(
            Invocation.method(#getFirebaseConfig, []),
            returnValue:
                _i4.Future<
                  _i5.Result<Map<String, dynamic>, _i7.AppError>
                >.value(
                  _i8.dummyValue<
                    _i5.Result<Map<String, dynamic>, _i7.AppError>
                  >(this, Invocation.method(#getFirebaseConfig, [])),
                ),
          )
          as _i4.Future<_i5.Result<Map<String, dynamic>, _i7.AppError>>);

  @override
  _i4.Future<_i5.Result<Map<String, dynamic>, _i7.AppError>> getSystemMetrics([
    String? window = '30m',
  ]) =>
      (super.noSuchMethod(
            Invocation.method(#getSystemMetrics, [window]),
            returnValue:
                _i4.Future<
                  _i5.Result<Map<String, dynamic>, _i7.AppError>
                >.value(
                  _i8.dummyValue<
                    _i5.Result<Map<String, dynamic>, _i7.AppError>
                  >(this, Invocation.method(#getSystemMetrics, [window])),
                ),
          )
          as _i4.Future<_i5.Result<Map<String, dynamic>, _i7.AppError>>);
}

/// A class which mocks [DioClient].
///
/// See the documentation for Mockito's code generation for more information.
class MockDioClient extends _i1.Mock implements _i15.DioClient {
  MockDioClient() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.Dio get dio =>
      (super.noSuchMethod(
            Invocation.getter(#dio),
            returnValue: _FakeDio_0(this, Invocation.getter(#dio)),
          )
          as _i2.Dio);

  @override
  void updateConfig(_i10.ConnectionConfig? config) => super.noSuchMethod(
    Invocation.method(#updateConfig, [config]),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [NotificationService].
///
/// See the documentation for Mockito's code generation for more information.
class MockNotificationService extends _i1.Mock
    implements _i16.NotificationService {
  MockNotificationService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Stream<Map<String, dynamic>> get onNotificationReceived =>
      (super.noSuchMethod(
            Invocation.getter(#onNotificationReceived),
            returnValue: _i4.Stream<Map<String, dynamic>>.empty(),
          )
          as _i4.Stream<Map<String, dynamic>>);

  @override
  bool get isInitialized =>
      (super.noSuchMethod(Invocation.getter(#isInitialized), returnValue: false)
          as bool);

  @override
  bool get dockerMonitoringEnabled =>
      (super.noSuchMethod(
            Invocation.getter(#dockerMonitoringEnabled),
            returnValue: false,
          )
          as bool);

  @override
  bool get resourceMonitoringEnabled =>
      (super.noSuchMethod(
            Invocation.getter(#resourceMonitoringEnabled),
            returnValue: false,
          )
          as bool);

  @override
  Map<String, double> get thresholds =>
      (super.noSuchMethod(
            Invocation.getter(#thresholds),
            returnValue: <String, double>{},
          )
          as Map<String, double>);

  @override
  _i4.Future<void> initialize() =>
      (super.noSuchMethod(
            Invocation.method(#initialize, []),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> registerForNotifications() =>
      (super.noSuchMethod(
            Invocation.method(#registerForNotifications, []),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> unregisterFromNotifications({String? baseUrl}) =>
      (super.noSuchMethod(
            Invocation.method(#unregisterFromNotifications, [], {
              #baseUrl: baseUrl,
            }),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> updateThresholds({
    double? cpuThreshold,
    double? memoryThreshold,
    double? gpuLoadThreshold,
    double? gpuMemoryThreshold,
    String? baseUrl,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#updateThresholds, [], {
              #cpuThreshold: cpuThreshold,
              #memoryThreshold: memoryThreshold,
              #gpuLoadThreshold: gpuLoadThreshold,
              #gpuMemoryThreshold: gpuMemoryThreshold,
              #baseUrl: baseUrl,
            }),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<Map<String, dynamic>> getMonitoringStatus() =>
      (super.noSuchMethod(
            Invocation.method(#getMonitoringStatus, []),
            returnValue: _i4.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i4.Future<Map<String, dynamic>>);

  @override
  _i4.Future<void> sendTestNotification(String? notificationType) =>
      (super.noSuchMethod(
            Invocation.method(#sendTestNotification, [notificationType]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> setNotificationPreferences({
    bool? dockerMonitoring,
    bool? resourceMonitoring,
    String? url,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#setNotificationPreferences, [], {
              #dockerMonitoring: dockerMonitoring,
              #resourceMonitoring: resourceMonitoring,
              #url: url,
            }),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> loadPreferences(String? url) =>
      (super.noSuchMethod(
            Invocation.method(#loadPreferences, [url]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> savePreferences(String? url) =>
      (super.noSuchMethod(
            Invocation.method(#savePreferences, [url]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> dispose() =>
      (super.noSuchMethod(
            Invocation.method(#dispose, []),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);
}

/// A class which mocks [ImageService].
///
/// See the documentation for Mockito's code generation for more information.
class MockImageService extends _i1.Mock implements _i17.ImageService {
  MockImageService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i5.Result<List<_i18.DockerImage>, _i7.AppError>> getImages() =>
      (super.noSuchMethod(
            Invocation.method(#getImages, []),
            returnValue:
                _i4.Future<
                  _i5.Result<List<_i18.DockerImage>, _i7.AppError>
                >.value(
                  _i8.dummyValue<
                    _i5.Result<List<_i18.DockerImage>, _i7.AppError>
                  >(this, Invocation.method(#getImages, [])),
                ),
          )
          as _i4.Future<_i5.Result<List<_i18.DockerImage>, _i7.AppError>>);

  @override
  _i4.Future<_i5.Result<bool, _i7.AppError>> pullImage(
    String? imageName,
    String? tag,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#pullImage, [imageName, tag]),
            returnValue: _i4.Future<_i5.Result<bool, _i7.AppError>>.value(
              _i8.dummyValue<_i5.Result<bool, _i7.AppError>>(
                this,
                Invocation.method(#pullImage, [imageName, tag]),
              ),
            ),
          )
          as _i4.Future<_i5.Result<bool, _i7.AppError>>);

  @override
  _i4.Future<_i5.Result<bool, _i7.AppError>> imageExists(
    String? imageName,
    String? tag,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#imageExists, [imageName, tag]),
            returnValue: _i4.Future<_i5.Result<bool, _i7.AppError>>.value(
              _i8.dummyValue<_i5.Result<bool, _i7.AppError>>(
                this,
                Invocation.method(#imageExists, [imageName, tag]),
              ),
            ),
          )
          as _i4.Future<_i5.Result<bool, _i7.AppError>>);

  @override
  _i4.Future<bool> ensureImageExists(String? imageName, String? tag) =>
      (super.noSuchMethod(
            Invocation.method(#ensureImageExists, [imageName, tag]),
            returnValue: _i4.Future<bool>.value(false),
          )
          as _i4.Future<bool>);

  @override
  _i4.Future<_i5.Result<bool, _i7.AppError>> removeImage(String? imageId) =>
      (super.noSuchMethod(
            Invocation.method(#removeImage, [imageId]),
            returnValue: _i4.Future<_i5.Result<bool, _i7.AppError>>.value(
              _i8.dummyValue<_i5.Result<bool, _i7.AppError>>(
                this,
                Invocation.method(#removeImage, [imageId]),
              ),
            ),
          )
          as _i4.Future<_i5.Result<bool, _i7.AppError>>);
}

/// A class which mocks [DockerService].
///
/// See the documentation for Mockito's code generation for more information.
class MockDockerService extends _i1.Mock implements _i19.DockerService {
  MockDockerService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i5.Result<_i2.Response<T>, _i7.AppError>> get<T>(
    String? path, {
    Map<String, dynamic>? queryParameters,
    _i2.Options? options,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #get,
              [path],
              {#queryParameters: queryParameters, #options: options},
            ),
            returnValue:
                _i4.Future<_i5.Result<_i2.Response<T>, _i7.AppError>>.value(
                  _i8.dummyValue<_i5.Result<_i2.Response<T>, _i7.AppError>>(
                    this,
                    Invocation.method(
                      #get,
                      [path],
                      {#queryParameters: queryParameters, #options: options},
                    ),
                  ),
                ),
          )
          as _i4.Future<_i5.Result<_i2.Response<T>, _i7.AppError>>);

  @override
  _i4.Future<_i5.Result<_i2.Response<T>, _i7.AppError>> post<T>(
    String? path, {
    dynamic data,
    Map<String, dynamic>? queryParameters,
    _i2.Options? options,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #post,
              [path],
              {
                #data: data,
                #queryParameters: queryParameters,
                #options: options,
              },
            ),
            returnValue:
                _i4.Future<_i5.Result<_i2.Response<T>, _i7.AppError>>.value(
                  _i8.dummyValue<_i5.Result<_i2.Response<T>, _i7.AppError>>(
                    this,
                    Invocation.method(
                      #post,
                      [path],
                      {
                        #data: data,
                        #queryParameters: queryParameters,
                        #options: options,
                      },
                    ),
                  ),
                ),
          )
          as _i4.Future<_i5.Result<_i2.Response<T>, _i7.AppError>>);

  @override
  _i4.Future<_i5.Result<_i2.Response<T>, _i7.AppError>> delete<T>(
    String? path, {
    dynamic data,
    Map<String, dynamic>? queryParameters,
    _i2.Options? options,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #delete,
              [path],
              {
                #data: data,
                #queryParameters: queryParameters,
                #options: options,
              },
            ),
            returnValue:
                _i4.Future<_i5.Result<_i2.Response<T>, _i7.AppError>>.value(
                  _i8.dummyValue<_i5.Result<_i2.Response<T>, _i7.AppError>>(
                    this,
                    Invocation.method(
                      #delete,
                      [path],
                      {
                        #data: data,
                        #queryParameters: queryParameters,
                        #options: options,
                      },
                    ),
                  ),
                ),
          )
          as _i4.Future<_i5.Result<_i2.Response<T>, _i7.AppError>>);
}

/// A class which mocks [VolumeService].
///
/// See the documentation for Mockito's code generation for more information.
class MockVolumeService extends _i1.Mock implements _i20.VolumeService {
  MockVolumeService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i5.Result<List<_i21.DockerVolume>, _i7.AppError>> getVolumes() =>
      (super.noSuchMethod(
            Invocation.method(#getVolumes, []),
            returnValue:
                _i4.Future<
                  _i5.Result<List<_i21.DockerVolume>, _i7.AppError>
                >.value(
                  _i8.dummyValue<
                    _i5.Result<List<_i21.DockerVolume>, _i7.AppError>
                  >(this, Invocation.method(#getVolumes, [])),
                ),
          )
          as _i4.Future<_i5.Result<List<_i21.DockerVolume>, _i7.AppError>>);

  @override
  _i4.Future<_i5.Result<bool, _i7.AppError>> createVolume(
    String? name, {
    String? driver = 'local',
    Map<String, String>? driverOpts,
    Map<String, String>? labels,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #createVolume,
              [name],
              {#driver: driver, #driverOpts: driverOpts, #labels: labels},
            ),
            returnValue: _i4.Future<_i5.Result<bool, _i7.AppError>>.value(
              _i8.dummyValue<_i5.Result<bool, _i7.AppError>>(
                this,
                Invocation.method(
                  #createVolume,
                  [name],
                  {#driver: driver, #driverOpts: driverOpts, #labels: labels},
                ),
              ),
            ),
          )
          as _i4.Future<_i5.Result<bool, _i7.AppError>>);

  @override
  _i4.Future<_i5.Result<bool, _i7.AppError>> removeVolume(String? name) =>
      (super.noSuchMethod(
            Invocation.method(#removeVolume, [name]),
            returnValue: _i4.Future<_i5.Result<bool, _i7.AppError>>.value(
              _i8.dummyValue<_i5.Result<bool, _i7.AppError>>(
                this,
                Invocation.method(#removeVolume, [name]),
              ),
            ),
          )
          as _i4.Future<_i5.Result<bool, _i7.AppError>>);
}

/// A class which mocks [NetworkService].
///
/// See the documentation for Mockito's code generation for more information.
class MockNetworkService extends _i1.Mock implements _i22.NetworkService {
  MockNetworkService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i5.Result<List<_i23.DockerNetwork>, _i7.AppError>>
  getNetworks() =>
      (super.noSuchMethod(
            Invocation.method(#getNetworks, []),
            returnValue:
                _i4.Future<
                  _i5.Result<List<_i23.DockerNetwork>, _i7.AppError>
                >.value(
                  _i8.dummyValue<
                    _i5.Result<List<_i23.DockerNetwork>, _i7.AppError>
                  >(this, Invocation.method(#getNetworks, [])),
                ),
          )
          as _i4.Future<_i5.Result<List<_i23.DockerNetwork>, _i7.AppError>>);

  @override
  _i4.Future<_i5.Result<bool, _i7.AppError>> createNetwork(
    String? name, {
    String? driver = 'bridge',
    Map<String, String>? options,
    Map<String, String>? labels,
    Map<String, dynamic>? ipam,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #createNetwork,
              [name],
              {
                #driver: driver,
                #options: options,
                #labels: labels,
                #ipam: ipam,
              },
            ),
            returnValue: _i4.Future<_i5.Result<bool, _i7.AppError>>.value(
              _i8.dummyValue<_i5.Result<bool, _i7.AppError>>(
                this,
                Invocation.method(
                  #createNetwork,
                  [name],
                  {
                    #driver: driver,
                    #options: options,
                    #labels: labels,
                    #ipam: ipam,
                  },
                ),
              ),
            ),
          )
          as _i4.Future<_i5.Result<bool, _i7.AppError>>);

  @override
  _i4.Future<_i5.Result<bool, _i7.AppError>> removeNetwork(String? name) =>
      (super.noSuchMethod(
            Invocation.method(#removeNetwork, [name]),
            returnValue: _i4.Future<_i5.Result<bool, _i7.AppError>>.value(
              _i8.dummyValue<_i5.Result<bool, _i7.AppError>>(
                this,
                Invocation.method(#removeNetwork, [name]),
              ),
            ),
          )
          as _i4.Future<_i5.Result<bool, _i7.AppError>>);

  @override
  _i4.Future<_i5.Result<_i23.DockerNetwork, _i7.AppError>> inspectNetwork(
    String? idOrName,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#inspectNetwork, [idOrName]),
            returnValue:
                _i4.Future<_i5.Result<_i23.DockerNetwork, _i7.AppError>>.value(
                  _i8.dummyValue<_i5.Result<_i23.DockerNetwork, _i7.AppError>>(
                    this,
                    Invocation.method(#inspectNetwork, [idOrName]),
                  ),
                ),
          )
          as _i4.Future<_i5.Result<_i23.DockerNetwork, _i7.AppError>>);
}

/// A class which mocks [Dio].
///
/// See the documentation for Mockito's code generation for more information.
class MockDio extends _i1.Mock implements _i2.Dio {
  MockDio() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.BaseOptions get options =>
      (super.noSuchMethod(
            Invocation.getter(#options),
            returnValue: _FakeBaseOptions_1(this, Invocation.getter(#options)),
          )
          as _i2.BaseOptions);

  @override
  _i2.HttpClientAdapter get httpClientAdapter =>
      (super.noSuchMethod(
            Invocation.getter(#httpClientAdapter),
            returnValue: _FakeHttpClientAdapter_2(
              this,
              Invocation.getter(#httpClientAdapter),
            ),
          )
          as _i2.HttpClientAdapter);

  @override
  _i2.Transformer get transformer =>
      (super.noSuchMethod(
            Invocation.getter(#transformer),
            returnValue: _FakeTransformer_3(
              this,
              Invocation.getter(#transformer),
            ),
          )
          as _i2.Transformer);

  @override
  _i2.Interceptors get interceptors =>
      (super.noSuchMethod(
            Invocation.getter(#interceptors),
            returnValue: _FakeInterceptors_4(
              this,
              Invocation.getter(#interceptors),
            ),
          )
          as _i2.Interceptors);

  @override
  set options(_i2.BaseOptions? _options) => super.noSuchMethod(
    Invocation.setter(#options, _options),
    returnValueForMissingStub: null,
  );

  @override
  set httpClientAdapter(_i2.HttpClientAdapter? _httpClientAdapter) =>
      super.noSuchMethod(
        Invocation.setter(#httpClientAdapter, _httpClientAdapter),
        returnValueForMissingStub: null,
      );

  @override
  set transformer(_i2.Transformer? _transformer) => super.noSuchMethod(
    Invocation.setter(#transformer, _transformer),
    returnValueForMissingStub: null,
  );

  @override
  void close({bool? force = false}) => super.noSuchMethod(
    Invocation.method(#close, [], {#force: force}),
    returnValueForMissingStub: null,
  );

  @override
  _i4.Future<_i2.Response<T>> head<T>(
    String? path, {
    Object? data,
    Map<String, dynamic>? queryParameters,
    _i2.Options? options,
    _i2.CancelToken? cancelToken,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #head,
              [path],
              {
                #data: data,
                #queryParameters: queryParameters,
                #options: options,
                #cancelToken: cancelToken,
              },
            ),
            returnValue: _i4.Future<_i2.Response<T>>.value(
              _FakeResponse_5<T>(
                this,
                Invocation.method(
                  #head,
                  [path],
                  {
                    #data: data,
                    #queryParameters: queryParameters,
                    #options: options,
                    #cancelToken: cancelToken,
                  },
                ),
              ),
            ),
          )
          as _i4.Future<_i2.Response<T>>);

  @override
  _i4.Future<_i2.Response<T>> headUri<T>(
    Uri? uri, {
    Object? data,
    _i2.Options? options,
    _i2.CancelToken? cancelToken,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #headUri,
              [uri],
              {#data: data, #options: options, #cancelToken: cancelToken},
            ),
            returnValue: _i4.Future<_i2.Response<T>>.value(
              _FakeResponse_5<T>(
                this,
                Invocation.method(
                  #headUri,
                  [uri],
                  {#data: data, #options: options, #cancelToken: cancelToken},
                ),
              ),
            ),
          )
          as _i4.Future<_i2.Response<T>>);

  @override
  _i4.Future<_i2.Response<T>> get<T>(
    String? path, {
    Object? data,
    Map<String, dynamic>? queryParameters,
    _i2.Options? options,
    _i2.CancelToken? cancelToken,
    _i2.ProgressCallback? onReceiveProgress,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #get,
              [path],
              {
                #data: data,
                #queryParameters: queryParameters,
                #options: options,
                #cancelToken: cancelToken,
                #onReceiveProgress: onReceiveProgress,
              },
            ),
            returnValue: _i4.Future<_i2.Response<T>>.value(
              _FakeResponse_5<T>(
                this,
                Invocation.method(
                  #get,
                  [path],
                  {
                    #data: data,
                    #queryParameters: queryParameters,
                    #options: options,
                    #cancelToken: cancelToken,
                    #onReceiveProgress: onReceiveProgress,
                  },
                ),
              ),
            ),
          )
          as _i4.Future<_i2.Response<T>>);

  @override
  _i4.Future<_i2.Response<T>> getUri<T>(
    Uri? uri, {
    Object? data,
    _i2.Options? options,
    _i2.CancelToken? cancelToken,
    _i2.ProgressCallback? onReceiveProgress,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #getUri,
              [uri],
              {
                #data: data,
                #options: options,
                #cancelToken: cancelToken,
                #onReceiveProgress: onReceiveProgress,
              },
            ),
            returnValue: _i4.Future<_i2.Response<T>>.value(
              _FakeResponse_5<T>(
                this,
                Invocation.method(
                  #getUri,
                  [uri],
                  {
                    #data: data,
                    #options: options,
                    #cancelToken: cancelToken,
                    #onReceiveProgress: onReceiveProgress,
                  },
                ),
              ),
            ),
          )
          as _i4.Future<_i2.Response<T>>);

  @override
  _i4.Future<_i2.Response<T>> post<T>(
    String? path, {
    Object? data,
    Map<String, dynamic>? queryParameters,
    _i2.Options? options,
    _i2.CancelToken? cancelToken,
    _i2.ProgressCallback? onSendProgress,
    _i2.ProgressCallback? onReceiveProgress,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #post,
              [path],
              {
                #data: data,
                #queryParameters: queryParameters,
                #options: options,
                #cancelToken: cancelToken,
                #onSendProgress: onSendProgress,
                #onReceiveProgress: onReceiveProgress,
              },
            ),
            returnValue: _i4.Future<_i2.Response<T>>.value(
              _FakeResponse_5<T>(
                this,
                Invocation.method(
                  #post,
                  [path],
                  {
                    #data: data,
                    #queryParameters: queryParameters,
                    #options: options,
                    #cancelToken: cancelToken,
                    #onSendProgress: onSendProgress,
                    #onReceiveProgress: onReceiveProgress,
                  },
                ),
              ),
            ),
          )
          as _i4.Future<_i2.Response<T>>);

  @override
  _i4.Future<_i2.Response<T>> postUri<T>(
    Uri? uri, {
    Object? data,
    _i2.Options? options,
    _i2.CancelToken? cancelToken,
    _i2.ProgressCallback? onSendProgress,
    _i2.ProgressCallback? onReceiveProgress,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #postUri,
              [uri],
              {
                #data: data,
                #options: options,
                #cancelToken: cancelToken,
                #onSendProgress: onSendProgress,
                #onReceiveProgress: onReceiveProgress,
              },
            ),
            returnValue: _i4.Future<_i2.Response<T>>.value(
              _FakeResponse_5<T>(
                this,
                Invocation.method(
                  #postUri,
                  [uri],
                  {
                    #data: data,
                    #options: options,
                    #cancelToken: cancelToken,
                    #onSendProgress: onSendProgress,
                    #onReceiveProgress: onReceiveProgress,
                  },
                ),
              ),
            ),
          )
          as _i4.Future<_i2.Response<T>>);

  @override
  _i4.Future<_i2.Response<T>> put<T>(
    String? path, {
    Object? data,
    Map<String, dynamic>? queryParameters,
    _i2.Options? options,
    _i2.CancelToken? cancelToken,
    _i2.ProgressCallback? onSendProgress,
    _i2.ProgressCallback? onReceiveProgress,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #put,
              [path],
              {
                #data: data,
                #queryParameters: queryParameters,
                #options: options,
                #cancelToken: cancelToken,
                #onSendProgress: onSendProgress,
                #onReceiveProgress: onReceiveProgress,
              },
            ),
            returnValue: _i4.Future<_i2.Response<T>>.value(
              _FakeResponse_5<T>(
                this,
                Invocation.method(
                  #put,
                  [path],
                  {
                    #data: data,
                    #queryParameters: queryParameters,
                    #options: options,
                    #cancelToken: cancelToken,
                    #onSendProgress: onSendProgress,
                    #onReceiveProgress: onReceiveProgress,
                  },
                ),
              ),
            ),
          )
          as _i4.Future<_i2.Response<T>>);

  @override
  _i4.Future<_i2.Response<T>> putUri<T>(
    Uri? uri, {
    Object? data,
    _i2.Options? options,
    _i2.CancelToken? cancelToken,
    _i2.ProgressCallback? onSendProgress,
    _i2.ProgressCallback? onReceiveProgress,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #putUri,
              [uri],
              {
                #data: data,
                #options: options,
                #cancelToken: cancelToken,
                #onSendProgress: onSendProgress,
                #onReceiveProgress: onReceiveProgress,
              },
            ),
            returnValue: _i4.Future<_i2.Response<T>>.value(
              _FakeResponse_5<T>(
                this,
                Invocation.method(
                  #putUri,
                  [uri],
                  {
                    #data: data,
                    #options: options,
                    #cancelToken: cancelToken,
                    #onSendProgress: onSendProgress,
                    #onReceiveProgress: onReceiveProgress,
                  },
                ),
              ),
            ),
          )
          as _i4.Future<_i2.Response<T>>);

  @override
  _i4.Future<_i2.Response<T>> patch<T>(
    String? path, {
    Object? data,
    Map<String, dynamic>? queryParameters,
    _i2.Options? options,
    _i2.CancelToken? cancelToken,
    _i2.ProgressCallback? onSendProgress,
    _i2.ProgressCallback? onReceiveProgress,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #patch,
              [path],
              {
                #data: data,
                #queryParameters: queryParameters,
                #options: options,
                #cancelToken: cancelToken,
                #onSendProgress: onSendProgress,
                #onReceiveProgress: onReceiveProgress,
              },
            ),
            returnValue: _i4.Future<_i2.Response<T>>.value(
              _FakeResponse_5<T>(
                this,
                Invocation.method(
                  #patch,
                  [path],
                  {
                    #data: data,
                    #queryParameters: queryParameters,
                    #options: options,
                    #cancelToken: cancelToken,
                    #onSendProgress: onSendProgress,
                    #onReceiveProgress: onReceiveProgress,
                  },
                ),
              ),
            ),
          )
          as _i4.Future<_i2.Response<T>>);

  @override
  _i4.Future<_i2.Response<T>> patchUri<T>(
    Uri? uri, {
    Object? data,
    _i2.Options? options,
    _i2.CancelToken? cancelToken,
    _i2.ProgressCallback? onSendProgress,
    _i2.ProgressCallback? onReceiveProgress,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #patchUri,
              [uri],
              {
                #data: data,
                #options: options,
                #cancelToken: cancelToken,
                #onSendProgress: onSendProgress,
                #onReceiveProgress: onReceiveProgress,
              },
            ),
            returnValue: _i4.Future<_i2.Response<T>>.value(
              _FakeResponse_5<T>(
                this,
                Invocation.method(
                  #patchUri,
                  [uri],
                  {
                    #data: data,
                    #options: options,
                    #cancelToken: cancelToken,
                    #onSendProgress: onSendProgress,
                    #onReceiveProgress: onReceiveProgress,
                  },
                ),
              ),
            ),
          )
          as _i4.Future<_i2.Response<T>>);

  @override
  _i4.Future<_i2.Response<T>> delete<T>(
    String? path, {
    Object? data,
    Map<String, dynamic>? queryParameters,
    _i2.Options? options,
    _i2.CancelToken? cancelToken,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #delete,
              [path],
              {
                #data: data,
                #queryParameters: queryParameters,
                #options: options,
                #cancelToken: cancelToken,
              },
            ),
            returnValue: _i4.Future<_i2.Response<T>>.value(
              _FakeResponse_5<T>(
                this,
                Invocation.method(
                  #delete,
                  [path],
                  {
                    #data: data,
                    #queryParameters: queryParameters,
                    #options: options,
                    #cancelToken: cancelToken,
                  },
                ),
              ),
            ),
          )
          as _i4.Future<_i2.Response<T>>);

  @override
  _i4.Future<_i2.Response<T>> deleteUri<T>(
    Uri? uri, {
    Object? data,
    _i2.Options? options,
    _i2.CancelToken? cancelToken,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #deleteUri,
              [uri],
              {#data: data, #options: options, #cancelToken: cancelToken},
            ),
            returnValue: _i4.Future<_i2.Response<T>>.value(
              _FakeResponse_5<T>(
                this,
                Invocation.method(
                  #deleteUri,
                  [uri],
                  {#data: data, #options: options, #cancelToken: cancelToken},
                ),
              ),
            ),
          )
          as _i4.Future<_i2.Response<T>>);

  @override
  _i4.Future<_i2.Response<dynamic>> download(
    String? urlPath,
    dynamic savePath, {
    _i2.ProgressCallback? onReceiveProgress,
    Map<String, dynamic>? queryParameters,
    _i2.CancelToken? cancelToken,
    bool? deleteOnError = true,
    _i2.FileAccessMode? fileAccessMode = _i2.FileAccessMode.write,
    String? lengthHeader = 'content-length',
    Object? data,
    _i2.Options? options,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #download,
              [urlPath, savePath],
              {
                #onReceiveProgress: onReceiveProgress,
                #queryParameters: queryParameters,
                #cancelToken: cancelToken,
                #deleteOnError: deleteOnError,
                #fileAccessMode: fileAccessMode,
                #lengthHeader: lengthHeader,
                #data: data,
                #options: options,
              },
            ),
            returnValue: _i4.Future<_i2.Response<dynamic>>.value(
              _FakeResponse_5<dynamic>(
                this,
                Invocation.method(
                  #download,
                  [urlPath, savePath],
                  {
                    #onReceiveProgress: onReceiveProgress,
                    #queryParameters: queryParameters,
                    #cancelToken: cancelToken,
                    #deleteOnError: deleteOnError,
                    #fileAccessMode: fileAccessMode,
                    #lengthHeader: lengthHeader,
                    #data: data,
                    #options: options,
                  },
                ),
              ),
            ),
          )
          as _i4.Future<_i2.Response<dynamic>>);

  @override
  _i4.Future<_i2.Response<dynamic>> downloadUri(
    Uri? uri,
    dynamic savePath, {
    _i2.ProgressCallback? onReceiveProgress,
    _i2.CancelToken? cancelToken,
    bool? deleteOnError = true,
    _i2.FileAccessMode? fileAccessMode = _i2.FileAccessMode.write,
    String? lengthHeader = 'content-length',
    Object? data,
    _i2.Options? options,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #downloadUri,
              [uri, savePath],
              {
                #onReceiveProgress: onReceiveProgress,
                #cancelToken: cancelToken,
                #deleteOnError: deleteOnError,
                #fileAccessMode: fileAccessMode,
                #lengthHeader: lengthHeader,
                #data: data,
                #options: options,
              },
            ),
            returnValue: _i4.Future<_i2.Response<dynamic>>.value(
              _FakeResponse_5<dynamic>(
                this,
                Invocation.method(
                  #downloadUri,
                  [uri, savePath],
                  {
                    #onReceiveProgress: onReceiveProgress,
                    #cancelToken: cancelToken,
                    #deleteOnError: deleteOnError,
                    #fileAccessMode: fileAccessMode,
                    #lengthHeader: lengthHeader,
                    #data: data,
                    #options: options,
                  },
                ),
              ),
            ),
          )
          as _i4.Future<_i2.Response<dynamic>>);

  @override
  _i4.Future<_i2.Response<T>> request<T>(
    String? url, {
    Object? data,
    Map<String, dynamic>? queryParameters,
    _i2.CancelToken? cancelToken,
    _i2.Options? options,
    _i2.ProgressCallback? onSendProgress,
    _i2.ProgressCallback? onReceiveProgress,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #request,
              [url],
              {
                #data: data,
                #queryParameters: queryParameters,
                #cancelToken: cancelToken,
                #options: options,
                #onSendProgress: onSendProgress,
                #onReceiveProgress: onReceiveProgress,
              },
            ),
            returnValue: _i4.Future<_i2.Response<T>>.value(
              _FakeResponse_5<T>(
                this,
                Invocation.method(
                  #request,
                  [url],
                  {
                    #data: data,
                    #queryParameters: queryParameters,
                    #cancelToken: cancelToken,
                    #options: options,
                    #onSendProgress: onSendProgress,
                    #onReceiveProgress: onReceiveProgress,
                  },
                ),
              ),
            ),
          )
          as _i4.Future<_i2.Response<T>>);

  @override
  _i4.Future<_i2.Response<T>> requestUri<T>(
    Uri? uri, {
    Object? data,
    _i2.CancelToken? cancelToken,
    _i2.Options? options,
    _i2.ProgressCallback? onSendProgress,
    _i2.ProgressCallback? onReceiveProgress,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #requestUri,
              [uri],
              {
                #data: data,
                #cancelToken: cancelToken,
                #options: options,
                #onSendProgress: onSendProgress,
                #onReceiveProgress: onReceiveProgress,
              },
            ),
            returnValue: _i4.Future<_i2.Response<T>>.value(
              _FakeResponse_5<T>(
                this,
                Invocation.method(
                  #requestUri,
                  [uri],
                  {
                    #data: data,
                    #cancelToken: cancelToken,
                    #options: options,
                    #onSendProgress: onSendProgress,
                    #onReceiveProgress: onReceiveProgress,
                  },
                ),
              ),
            ),
          )
          as _i4.Future<_i2.Response<T>>);

  @override
  _i4.Future<_i2.Response<T>> fetch<T>(_i2.RequestOptions? requestOptions) =>
      (super.noSuchMethod(
            Invocation.method(#fetch, [requestOptions]),
            returnValue: _i4.Future<_i2.Response<T>>.value(
              _FakeResponse_5<T>(
                this,
                Invocation.method(#fetch, [requestOptions]),
              ),
            ),
          )
          as _i4.Future<_i2.Response<T>>);

  @override
  _i2.Dio clone({
    _i2.BaseOptions? options,
    _i2.Interceptors? interceptors,
    _i2.HttpClientAdapter? httpClientAdapter,
    _i2.Transformer? transformer,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#clone, [], {
              #options: options,
              #interceptors: interceptors,
              #httpClientAdapter: httpClientAdapter,
              #transformer: transformer,
            }),
            returnValue: _FakeDio_0(
              this,
              Invocation.method(#clone, [], {
                #options: options,
                #interceptors: interceptors,
                #httpClientAdapter: httpClientAdapter,
                #transformer: transformer,
              }),
            ),
          )
          as _i2.Dio);
}

/// A class which mocks [ConnectionStorageService].
///
/// See the documentation for Mockito's code generation for more information.
class MockConnectionStorageService extends _i1.Mock
    implements _i24.ConnectionStorageService {
  MockConnectionStorageService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<void> saveConnectionConfig(_i10.ConnectionConfig? config) =>
      (super.noSuchMethod(
            Invocation.method(#saveConnectionConfig, [config]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<_i10.ConnectionConfig?> loadConnectionConfig() =>
      (super.noSuchMethod(
            Invocation.method(#loadConnectionConfig, []),
            returnValue: _i4.Future<_i10.ConnectionConfig?>.value(),
          )
          as _i4.Future<_i10.ConnectionConfig?>);

  @override
  _i4.Future<void> deleteConnectionConfig() =>
      (super.noSuchMethod(
            Invocation.method(#deleteConnectionConfig, []),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> saveConnectionHistory(List<String>? history) =>
      (super.noSuchMethod(
            Invocation.method(#saveConnectionHistory, [history]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<List<String>> loadConnectionHistory() =>
      (super.noSuchMethod(
            Invocation.method(#loadConnectionHistory, []),
            returnValue: _i4.Future<List<String>>.value(<String>[]),
          )
          as _i4.Future<List<String>>);

  @override
  _i4.Future<void> deleteConnectionHistory() =>
      (super.noSuchMethod(
            Invocation.method(#deleteConnectionHistory, []),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);
}

/// A class which mocks [PreferencesService].
///
/// See the documentation for Mockito's code generation for more information.
class MockPreferencesService extends _i1.Mock
    implements _i25.PreferencesService {
  MockPreferencesService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  bool getBool(String? key, {bool? defaultValue = false}) =>
      (super.noSuchMethod(
            Invocation.method(#getBool, [key], {#defaultValue: defaultValue}),
            returnValue: false,
          )
          as bool);

  @override
  _i4.Future<bool> setBool(String? key, bool? value) =>
      (super.noSuchMethod(
            Invocation.method(#setBool, [key, value]),
            returnValue: _i4.Future<bool>.value(false),
          )
          as _i4.Future<bool>);

  @override
  double getDouble(String? key, {double? defaultValue = 0.0}) =>
      (super.noSuchMethod(
            Invocation.method(#getDouble, [key], {#defaultValue: defaultValue}),
            returnValue: 0.0,
          )
          as double);

  @override
  _i4.Future<bool> setDouble(String? key, double? value) =>
      (super.noSuchMethod(
            Invocation.method(#setDouble, [key, value]),
            returnValue: _i4.Future<bool>.value(false),
          )
          as _i4.Future<bool>);

  @override
  String getString(String? key, {String? defaultValue = ''}) =>
      (super.noSuchMethod(
            Invocation.method(#getString, [key], {#defaultValue: defaultValue}),
            returnValue: _i8.dummyValue<String>(
              this,
              Invocation.method(
                #getString,
                [key],
                {#defaultValue: defaultValue},
              ),
            ),
          )
          as String);

  @override
  _i4.Future<bool> setString(String? key, String? value) =>
      (super.noSuchMethod(
            Invocation.method(#setString, [key, value]),
            returnValue: _i4.Future<bool>.value(false),
          )
          as _i4.Future<bool>);

  @override
  List<String> getStringList(
    String? key, {
    List<String>? defaultValue = const [],
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #getStringList,
              [key],
              {#defaultValue: defaultValue},
            ),
            returnValue: <String>[],
          )
          as List<String>);

  @override
  _i4.Future<bool> setStringList(String? key, List<String>? value) =>
      (super.noSuchMethod(
            Invocation.method(#setStringList, [key, value]),
            returnValue: _i4.Future<bool>.value(false),
          )
          as _i4.Future<bool>);

  @override
  _i4.Future<bool> remove(String? key) =>
      (super.noSuchMethod(
            Invocation.method(#remove, [key]),
            returnValue: _i4.Future<bool>.value(false),
          )
          as _i4.Future<bool>);
}

/// A class which mocks [FirebaseService].
///
/// See the documentation for Mockito's code generation for more information.
class MockFirebaseService extends _i1.Mock implements _i26.FirebaseService {
  MockFirebaseService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<void> initialize(Map<String, dynamic>? config) =>
      (super.noSuchMethod(
            Invocation.method(#initialize, [config]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> terminate() =>
      (super.noSuchMethod(
            Invocation.method(#terminate, []),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);
}
